define(function (require, exports) {
  var Ubb = require('./Ubb').Ubb;
  var font = require('./tags/font');
  var layout = require('./tags/layout');
  var list = require('./tags/list');
  var img = require('./tags/img');
  var ubb = new Ubb();
  ubb.set(font.b);
  ubb.set(font.u);
  ubb.set(font.i);
  ubb.set(font.del);
  ubb.set(font.h);
  ubb.set(font.font);
  ubb.set(font.color);
  ubb.set(font.size);
  ubb.set(font.align);
  ubb.set(layout.l);
  ubb.set(layout.r);
  ubb.set(layout.quote);
  ubb.set(layout.code);
  ubb.set(list.list);
  ubb.set(img.img);
  return ubb;
});